### PR TITLE
Added a toasted message on success

### PR DESCRIPTION
**Pull request by irfanm96**
The update was working fine, but there was no indication that the entry was updated or not, so to fix it, added a simple toast message on success.

### CODE REVIEW

**Comment by Frozire** [comment]
Hey @PatricNox 

Anything we can do to help get this merged?

**Comment by PatricNox** [comment]
@Frozire I don't really have an say about anything in this repository. 

@msassa is the sole authorized man as its he who created this package.

**Comment by Frozire** [comment]
@PatricNox Sorry, I missaw "Author" tag on another PR, and now just realise you just contributed that PR. My bad.

**Comment by msassa** [comment]
Sorry for the delay. I'm to busy.

**Pull request merged**
